// <auto-generated />
using System;
using LuminaBeauty.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuminaBeauty.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LuminaBeauty.API.Models.Coupon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("LuminaBeauty.API.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complement")
                        .HasColumnType("TEXT");

                    b.Property<string>("CouponCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shipping")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LuminaBeauty.API.Models.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("LuminaBeauty.API.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "colar-rose",
                            Category = "Acessórios",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Banho rosé delicado com ponto de luz central.",
                            ImageUrl = "colar-rose.jpg",
                            Name = "Colar Rosé Lumina",
                            Price = 129.90m,
                            Stock = 18,
                            Subcategory = "colares"
                        },
                        new
                        {
                            Id = "brincos-perola",
                            Category = "Acessórios",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pérolas sintéticas com acabamento dourado leve.",
                            ImageUrl = "brincos-perola.jpg",
                            Name = "Brincos Pérola Aurora",
                            Price = 89.90m,
                            Stock = 24,
                            Subcategory = "brincos"
                        },
                        new
                        {
                            Id = "anel-ouro",
                            Category = "Acessórios",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aro ajustável com brilho sutil para o dia a dia.",
                            ImageUrl = "anel-ouro.jpg",
                            Name = "Anel Dourado Essencial",
                            Price = 79.90m,
                            Stock = 20,
                            Subcategory = "anéis"
                        },
                        new
                        {
                            Id = "base-pele",
                            Category = "Beleza",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cobertura média com acabamento luminoso.",
                            ImageUrl = "base-pele.jpg",
                            Name = "Base Skin Glow",
                            Price = 119.90m,
                            Stock = 30,
                            Subcategory = "rosto"
                        },
                        new
                        {
                            Id = "paleta-olhos",
                            Category = "Beleza",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tons neutros, acetinados e matte para composições elegantes.",
                            ImageUrl = "paleta-olhos.jpg",
                            Name = "Paleta Nude Poésie",
                            Price = 149.90m,
                            Stock = 15,
                            Subcategory = "olhos"
                        },
                        new
                        {
                            Id = "batom-rose",
                            Category = "Beleza",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Textura confortável com cor rosada sofisticada.",
                            ImageUrl = "batom-rose.jpg",
                            Name = "Batom Rose Velours",
                            Price = 59.90m,
                            Stock = 34,
                            Subcategory = "lábios"
                        },
                        new
                        {
                            Id = "pinceis",
                            Category = "Beleza",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kit versátil para pele, olhos e acabamento.",
                            ImageUrl = "pinceis.jpg",
                            Name = "Kit Pincéis Soft Touch",
                            Price = 179.90m,
                            Stock = 12,
                            Subcategory = "pincéis"
                        },
                        new
                        {
                            Id = "limpeza-facial",
                            Category = "Skincare",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Limpeza suave para rotina diária de skincare.",
                            ImageUrl = "limpeza-facial.jpg",
                            Name = "Gel de Limpeza Floral",
                            Price = 69.90m,
                            Stock = 28,
                            Subcategory = "limpeza"
                        },
                        new
                        {
                            Id = "hidratante",
                            Category = "Skincare",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hidratação leve com toque aveludado.",
                            ImageUrl = "hidratante.jpg",
                            Name = "Hidratante Cloud Cream",
                            Price = 99.90m,
                            Stock = 22,
                            Subcategory = "hidratação"
                        },
                        new
                        {
                            Id = "mascara-facial",
                            Category = "Skincare",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Máscara revitalizante para efeito glow imediato.",
                            ImageUrl = "mascara-facial.jpg",
                            Name = "Máscara Facial Radiance",
                            Price = 49.90m,
                            Stock = 40,
                            Subcategory = "máscaras"
                        },
                        new
                        {
                            Id = "serum",
                            Category = "Skincare",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sérum antioxidante para uniformizar o viço da pele.",
                            ImageUrl = "serum.jpg",
                            Name = "Sérum Vitamina C Lumi",
                            Price = 139.90m,
                            Stock = 16,
                            Subcategory = "séruns"
                        },
                        new
                        {
                            Id = "protetor-solar",
                            Category = "Skincare",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "FPS alto com acabamento invisível e confortável.",
                            ImageUrl = "protetor-solar.jpg",
                            Name = "Protetor Solar Toque Seco",
                            Price = 84.90m,
                            Stock = 26,
                            Subcategory = "proteção solar"
                        });
                });

            modelBuilder.Entity("LuminaBeauty.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "seed-admin-001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "gerencia@lumina.com.br",
                            FullName = "Gerência Lumina",
                            PasswordHash = "$2a$11$Cl7dNWUpiUpqJ8f0kP2dOe6ZZJyC3xlWOEYcV6Xx.er8OEbMn6FwS",
                            Phone = "",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("LuminaBeauty.API.Models.Order", b =>
                {
                    b.HasOne("LuminaBeauty.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaBeauty.API.Models.OrderItem", b =>
                {
                    b.HasOne("LuminaBeauty.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LuminaBeauty.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LuminaBeauty.API.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
